# Generated by Django 3.1.7 on 2021-03-07 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fio', models.CharField(default='', max_length=70)),
                ('phone', models.CharField(default='', max_length=70)),
                ('address', models.CharField(default='', max_length=70)),
                ('inn', models.CharField(default='', max_length=10)),
            ],
        ),
    ]
